# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CarsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CarsDemo

  pod 'AlamofireImage', '~> 4.1'

  target 'CarsDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CarsDemoUITests' do
    # Pods for testing
  end

end
